# Run Linters for code checks on every PR open (Eslint and StyleLint)
# Might add on push later if possible base on activity
name: Codebase Checker

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.14.1'

    - name: Cache npm Dependencies
      uses: actions/cache@v2
      id: cache_npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-cache_npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Cache Node Modules
      uses: actions/cache@v2
      id: cache_node_modules
      with:
        path: node_modules
        key: ${{ runner.os }}-cache_node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies # https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
      run: |
        npm ci
      if: steps.cache_node_modules.outputs.cache-hit != 'true' # skip this step if cacher restored

    - name: Validate Javascript files with Eslint
      run: |
        npm run jsLint

    - name: Validate CSS and Styled Component code with StyleLint
      run: |
        npm run cssLint
